# The URL the site will be built for
base_url = "https://kemingy.github.io/nutshell/"

compile_sass = true
generate_rss = true

title = "Nutshell"
description = ""

highlight_code = true
highlight_theme = "Tomorrow"


taxonomies = [
    {name = "categories", rss = true},
]

[extra]
theme_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/archive", name = "Archive"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/projects", name = "Projects"},
]
katex = true
